#!/bin/sh

# find if a commit is in first-parents

base=$1

branches=`git branch --contains $base | cut -c 3- `
prev=$(git rev-parse $base^)

for br in $branches; do
    if git rev-list --no-merges --first-parent $prev..$br | grep -q $base; then
        echo "branch : "$br
    fi
done
