# This is a basic workflow to help you get started with Actions

name: 'Pull Request Commit Message Check'

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Get PR Commits
        id: 'get-pr-commits'
        uses: tim-actions/get-pr-commits@3efc1387ead42029a0d488ab98f24b7452dc3cde # v1.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Title
        uses: tim-actions/commit-message-checker-with-regex@094fc16ff83d04e2ec73edb5eaf6aa267db33791 # v0.3.2
        with:
          commits: ${{ steps.get-pr-commits.outputs.commits }}
          pattern: '^[a-z]+\([a-z]+\): .+(\n.*)*$'
          error: 'Title likes `<type>(<scope>): <subject>`'

      - name: Check Subject Line Length
        uses: tim-actions/commit-message-checker-with-regex@094fc16ff83d04e2ec73edb5eaf6aa267db33791 # v0.3.2
        with:
          commits: ${{ steps.get-pr-commits.outputs.commits }}
          pattern: '^.{0,100}(\n.*)*$'
          error: 'Subject too long (max 100)'

      - name: Check Body Line Length
        uses: tim-actions/commit-message-checker-with-regex@094fc16ff83d04e2ec73edb5eaf6aa267db33791 # v0.3.2
        with:
          commits: ${{ steps.get-pr-commits.outputs.commits }}
          pattern: '^.+(\n.{0,2048})*$'
          error: 'Body line too long (max 2048)'
